const algosdk = require("algosdk");
const address = require('./node_modules/algosdk/src/encoding/address')

// Transaction bytes string encoded in base64, as generated by the JS into the blob field
tx_base64 = undefined; //"gqNzaWfEQAk..." 

if(tx_base64){
    try{
        tx = algosdk.decodeObj(new Uint8Array(Buffer.from(tx_base64, "base64")));
        console.log(`Note: ${Buffer.from(tx.txn.note, "base64").toString()}`);
        console.log(`From: ${address.encode(tx.txn.snd)}`);
        console.log(`Amount: ${tx.txn.amt.toString()} microAlgos`);
    }
    catch{
        console.log(`Error decoding the base 64 transaction.`);
    }
}
else{
    console.log(`Base 64 transaction not defined.`);
}